// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Post {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	excerpt?: string;
	body?: PortableTextBlock[];
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	bylines?: ContentBylineCredit[];
}

export interface Service {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	excerpt?: string;
	body?: PortableTextBlock[];
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	bylines?: ContentBylineCredit[];
}

export interface Page {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	body?: PortableTextBlock[];
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	bylines?: ContentBylineCredit[];
}

declare module "emdash" {
	interface EmDashCollections {
		posts: Post;
		services: Service;
		pages: Page;
	}
}
